# Ejercicios de Pandas

Estos ejercicios te ayudarán a practicar los conceptos de Pandas usando el dataset del Titanic.

**Instrucciones:**
- Completa cada ejercicio escribiendo el código en las celdas correspondientes
- Ejecuta las celdas para verificar tus resultados
- Si necesitas ayuda, revisa los notebooks de fundamentos de Pandas

In [2]:
# Importar librerías y cargar datos
import pandas as pd
import numpy as np

# Cargar el dataset del Titanic
titanic = pd.read_csv('titanic.csv')
print(f"Dataset cargado: {titanic.shape}")

Dataset cargado: (891, 12)

## Ejercicio 1: Exploración básica

Realiza una exploración inicial del dataset:

1. Muestra las primeras 7 filas
2. Muestra las últimas 5 filas
3. Obtén información general del DataFrame (info())
4. Muestra las estadísticas descriptivas de las columnas numéricas
5. ¿Cuántas filas y columnas tiene el dataset?

In [6]:
# Tu código aquí

# 1. Primeras 7 filas
titanic.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712.833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,08.05,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,518.625,E46,S

In [9]:
# 2. Últimas 5 filas
titanic.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [16]:
# 3. Información general
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    object
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

In [13]:
# 4. Estadísticas descriptivas
titanic.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000

In [21]:
# 5. Número de filas y columnas
print ("El total de filas y columnas es :",titanic.shape)

El total de filas y columnas es : (891, 12)

## Ejercicio 2: Selección de datos

Practica la selección de columnas y filas:

1. Selecciona solo la columna 'Name' (como Series)
2. Selecciona las columnas 'Name', 'Age' y 'Sex' (como DataFrame)
3. Usando iloc, selecciona las filas 10 a 15 y las primeras 5 columnas
4. Usando loc, selecciona las filas 0 a 9 y las columnas 'Name', 'Age', 'Survived'
5. Selecciona la fila con índice 100

In [26]:
# Tu código aquí
# 1. Columna 'Name' como Series
titanic['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# 2. Múltiples columnas como DataFrame
df_filtrado = titanic[['Name','Sex','Age']]
print(df_filtrado)

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [ ]:
# 3. iloc - filas 10-15, primeras 5 columnas
titanic.iloc[10:16, :5]

,PassengerId,Survived,Pclass,Name,Sex
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female
11,12,1,1,"Bonnell, Miss. Elizabeth",female
12,13,0,3,"Saundercock, Mr. William Henry",male
13,14,0,3,"Andersson, Mr. Anders Johan",male
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female

In [38]:
# 4. loc - filas 0-9, columnas específicas
titanic.loc[0:9, ['Name', 'Sex', 'Age']]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [11]:
# 5. Fila con índice 100
titanic.loc[100]

PassengerId                        101
Survived                             0
Pclass                               3
Name           Petranec, Miss. Matilda
Sex                             female
Age                               28.0
SibSp                                0
Parch                                0
Ticket                          349245
Fare                             78958
Cabin                              NaN
Embarked                             S
Name: 100, dtype: object

## Ejercicio 3: Filtrado básico

Aplica filtros para encontrar información específica:

1. ¿Cuántos pasajeros sobrevivieron? (Survived = 1)
2. ¿Cuántas mujeres había en el barco?
3. ¿Cuántos pasajeros de primera clase había?
4. Encuentra todos los pasajeros menores de 18 años
5. ¿Cuántos pasajeros pagaron más de 100 en tarifa?
6. Muestra los nombres de los primeros 5 pasajeros menores de 18 años

In [8]:
# Tu código aquí

# 1. Pasajeros que sobrevivieron
sobrevivientes = titanic['Survived'].value_counts()[1]
print("Sobrevivieron: ",sobrevivientes," pasajeros")
# 2. Mujeres en el barco
mujeres = titanic['Sex'].value_counts()['female']
print("El total de mujeres en el titanic es de : ",mujeres)
# 3. Pasajeros de primera clase
pasajeros_primera = titanic['Pclass'].value_counts()[1]
print("Pasajeros de primera clase: ",pasajeros_primera)
# 4. Menores de 18 años
pasajeros_menores = titanic[titanic['Age']<18]
print("Pasajeros menores de 18 años: ",len(pasajeros_menores))
# 5. Tarifa mayor a 100
titanic['Fare'] = (
   titanic['Fare']
    .astype(str)
    .str.replace('.' , '') 
    )
titanic ['Fare'] = pd.to_numeric (titanic['Fare'])
tarifas_altas = len(titanic[titanic['Fare'] > 100])
print ("Pasajeros con tarifa mayor a 100: ",tarifas_altas)
# 6. Nombres de los primeros 5 menores de 18
print("Los nombres de los primeros 5 pasajeros menores de 18 años son: ", pasajeros_menores['Name'].head(5))

Sobrevivieron:  342  pasajeros
El total de mujeres en el titanic es de :  314
Pasajeros de primera clase:  216
Pasajeros menores de 18 años:  113
Pasajeros con tarifa mayor a 100:  727
Los nombres de los primeros 5 pasajeros menores de 18 años son:  7           Palsson, Master. Gosta Leonard
9      Nasser, Mrs. Nicholas (Adele Achem)
10         Sandstrom, Miss. Marguerite Rut
14    Vestrom, Miss. Hulda Amanda Adolfina
16                    Rice, Master. Eugene
Name: Name, dtype: object

## Ejercicio 4: Filtrado avanzado

Combina múltiples condiciones:

1. Mujeres que sobrevivieron
2. Hombres de primera clase que no sobrevivieron
3. Pasajeros entre 20 y 40 años (inclusive) que sobrevivieron
4. Pasajeros que embarcaron en 'S' o 'C' (usa isin())
5. Pasajeros cuyo nombre contiene 'Mrs.' (usa str.contains())
6. ¿Cuál fue la tasa de supervivencia de las mujeres vs los hombres?

In [26]:
# Tu código aquí

# 1. Mujeres que sobrevivieron
mujeres_sobrevivientes = titanic[(titanic['Sex'] == 'female') & (titanic['Survived'] == 1)]
print("Mujeres que sobrevivieron: ",len(mujeres_sobrevivientes))
# 2. Hombres de primera clase que no sobrevivieron
hombres_primera_no_sobrevivientes = titanic[(titanic['Sex'] == 'male') & (titanic['Pclass'] == 1) & (titanic['Survived'] == 0)]
print("Hombres de primera clase que no sobrevivieron: ",len(hombres_primera_no_sobrevivientes))
# 3. Edad 20-40 que sobrevivieron
jovenes_sobrevivientes = titanic[(titanic['Age']>=20)  & (titanic['Age']<=40) & (titanic['Survived']==1)]
print("Sobrevivientes entre 20 y 40 años: ",len(jovenes_sobrevivientes))
# 4. Embarcaron en 'S' o 'C'
embarcaron_sc = titanic[(titanic['Embarked']=='S') | (titanic['Embarked']=='C')]
print("Pasajeros en clase S o C: ",len(embarcaron_sc))
# 5. Nombres con 'Mrs.'
nombre_mrs = titanic[titanic['Name'].str.contains('Mrs.')]
print("Nombres que contiene Mrs",len(nombre_mrs))
# 6. Tasa de supervivencia por sexo
tada_supervivencia_sexo = titanic.groupby('Sex')['Survived'].mean()*100
print("Tasa de supervivencia por sexo:\n",tada_supervivencia_sexo)

Mujeres que sobrevivieron:  233
Hombres de primera clase que no sobrevivieron:  77
Sobrevivientes entre 20 y 40 años:  156
Pasajeros en clase S o C:  812
Nombres que contiene Mrs 129
Tasa de supervivencia por sexo:
 Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

## Ejercicio 5: Estadísticas y agrupaciones

Calcula estadísticas descriptivas:

1. ¿Cuál es la edad promedio de todos los pasajeros?
2. ¿Cuál es la tarifa más alta y más baja pagada?
3. ¿Cuántos pasajeros hay de cada clase? (value_counts)
4. ¿Cuál es la edad promedio por clase? (groupby)
5. ¿Cuál es la tarifa promedio por puerto de embarque?
6. Crea una tabla que muestre la cantidad de sobrevivientes y no sobrevivientes por sexo

In [1]:
# Tu código aquí

# 1. Edad promedio
edad_promedio = titanic['Age'].mean()
print("Edad promedio de los pasajeros: ",round(edad_promedio,2))
# 2. Tarifa máxima y mínima
tarifa_maxima = titanic['Fare'].max()
tarifa_minima = titanic['Fare'].min()
print("La tarifa máxima es: ",tarifa_maxima)
print("La tarifa mínima es: ",tarifa_minima)
# 3. Pasajeros por clase
pasajero_clase = (titanic['Pclass']).value_counts()
print("Los pasajeros por las diferentes clases son\n",pasajero_clase)
# 4. Edad promedio por clase
edad_pomedio = titanic.groupby('Pclass')['Age'].mean()
print("Edad promedio por clase:\n",edad_pomedio)
# 5. Tarifa promedio por puerto
titanic['Fare'] = (
   titanic['Fare']
    .astype(str)
    .str.replace('.' , '') 
    )
titanic ['Fare'] = pd.to_numeric (titanic['Fare'])
promedio_por_puerto = titanic.groupby('Embarked')['Fare'].mean()
print("Tarifa promedio por puerto:\n",round(promedio_por_puerto,2))
# 6. Supervivencia por sexo
supervivencia_por_sexo = titanic.groupby('Sex')['Survived'].mean()*100
print("Tasa de supervivencia por sexo:\n",supervivencia_por_sexo)
#crosstab
pd.crosstab(titanic['Sex'],titanic['Survived'])

NameError: name 'titanic' is not defined

## Ejercicio 6: Crear nuevas columnas

Manipula el DataFrame creando nuevas columnas:

1. Crea una columna 'Family_Size' que sume SibSp + Parch + 1
2. Crea una columna 'Age_Group' con las categorías:
   - 'Child' (< 18 años)
   - 'Adult' (18-59 años)
   - 'Senior' (>= 60 años)
   - 'Unknown' (edad faltante)
3. Crea una columna 'Fare_Category' con:
   - 'Low' (Fare < 10)
   - 'Medium' (10 <= Fare < 50)
   - 'High' (Fare >= 50)
4. Crea una columna 'Title' que extraiga el título del nombre (Mr., Mrs., Miss., etc.)
5. Muestra las primeras 10 filas con las nuevas columnas

In [ ]:
# Crear una copia para no modificar el original
titanic_trabajo = titanic.copy()

# Tu código aquí

# 1. Family_Size
titanic_trabajo['Family_Size'] = titanic_trabajo['SibSp'] + titanic_trabajo['Parch'] + 1
titanic_trabajo.head()
# 2. Age_Group
titanic_trabajo['Age_Group'] = pd.cut(
    titanic_trabajo['Age'],
    bins=[0, 18, 59, 120],
    labels=['Child', 'Adult', 'Senior']
)
# Añadimos a mano el 'Unknown' si es nulo, en esto caso los nulos son 'Unknown'
titanic_trabajo['Age_Group'] = titanic_trabajo['Age_Group'].cat.add_categories('Unknown').fillna('Unknown')
titanic_trabajo.head()

<>:34: SyntaxWarning: invalid escape sequence '\.'
<>:34: SyntaxWarning: invalid escape sequence '\.'
C:\Users\USER\AppData\Local\Temp\ipykernel_18368\2674281655.py:34: SyntaxWarning: invalid escape sequence '\.'
  titanic_trabajo['Title'] = titanic_trabajo['Name'].str.extract(' ([A-Za-z]+)\.')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Age_Group,Fare_Category,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,725,NaN,S,2,Adult,High,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833,C85,C,2,Adult,High,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925,NaN,S,1,Adult,High,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,531,C123,S,2,Adult,High,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,805,NaN,S,1,Adult,High,Mr
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,84583,NaN,Q,1,Unknown,High,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,518625,E46,S,1,Adult,High,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21075,NaN,S,5,Child,High,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,111333,NaN,S,3,Adult,High,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,300708,NaN,C,2,Child,High,Mrs

In [15]:
# 3. Fare_Category
titanic['Fare'] = (
   titanic['Fare']
    .astype(str)
    .str.replace('.' , '') 
    )
titanic ['Fare'] = pd.to_numeric (titanic['Fare'])
titanic_trabajo['Fare_Category'] = pd.cut(
    titanic['Fare'],
    bins=[-1, 10, 50, float('inf')],
    labels=['Low', 'Medium', 'High']
)
titanic_trabajo.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Age_Group,Fare_Category,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,725,NaN,S,2,Adult,High,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833,C85,C,2,Adult,High,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925,NaN,S,1,Adult,High,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,531,C123,S,2,Adult,High,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,805,NaN,S,1,Adult,High,Mr

In [16]:
# 4. Title (pista: usa str.extract con regex)
titanic_trabajo['Title'] = titanic_trabajo['Name'].str.extract(' ([A-Za-z]+)\.')
# 5. Mostrar primeras 10 filas con nuevas columnas
titanic_trabajo.head(10)

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
C:\Users\USER\AppData\Local\Temp\ipykernel_18368\3120501899.py:2: SyntaxWarning: invalid escape sequence '\.'
  titanic_trabajo['Title'] = titanic_trabajo['Name'].str.extract(' ([A-Za-z]+)\.')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Age_Group,Fare_Category,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,725,NaN,S,2,Adult,High,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833,C85,C,2,Adult,High,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925,NaN,S,1,Adult,High,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,531,C123,S,2,Adult,High,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,805,NaN,S,1,Adult,High,Mr
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,84583,NaN,Q,1,Unknown,High,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,518625,E46,S,1,Adult,High,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21075,NaN,S,5,Child,High,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,111333,NaN,S,3,Adult,High,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,300708,NaN,C,2,Child,High,Mrs

## Ejercicio 7: Análisis de valores faltantes

Analiza los datos faltantes en el dataset:

1. ¿Qué columnas tienen valores faltantes y cuántos?
2. ¿Qué porcentaje de valores faltantes tiene cada columna?
3. ¿Cuántas filas tienen al menos un valor faltante?
4. Muestra 5 ejemplos de filas que tienen edad faltante
5. ¿Hay algún patrón en los valores faltantes de edad por clase?

In [15]:
# Tu código aquí

# 1. Valores faltantes por columna
faltantes_por_columna = titanic_trabajo.isnull().sum()
print("Valores faltantes por columna:\n",faltantes_por_columna)
# 2. Porcentaje de valores faltantes
faltantes_porcentaje = titanic_trabajo.isnull().mean() * 100
print("\nPorcentaje de valores faltantes por columna (%):\n", faltantes_porcentaje.round(2))

Valores faltantes por columna:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Family_Size      0
Age_Group        0
Title            0
dtype: int64

Porcentaje de valores faltantes por columna (%):
 PassengerId     0.00
Survived        0.00
Pclass          0.00
Name            0.00
Sex             0.00
Age            19.87
SibSp           0.00
Parch           0.00
Ticket          0.00
Fare            0.00
Cabin          77.10
Embarked        0.22
Family_Size     0.00
Age_Group       0.00
Title           0.00
dtype: float64

In [20]:
# 3. Filas con al menos un valor faltante
faltantes_filas = titanic_trabajo.isnull().any(axis=1)
faltantes_filas_sum = faltantes_filas.sum()
print("\nNúmero de filas con al menos un valor faltante:", faltantes_filas_sum)

 
# 4. Ejemplos de filas con edad faltante
ejemplos_edad_faltante = titanic_trabajo[titanic_trabajo['Age'].isnull()]
print("\nEjemplos de filas con edad faltante:\n", ejemplos_edad_faltante)

Número de filas con al menos un valor faltante: 708

Ejemplos de filas con edad faltante:
      PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James
17            18         1       2              Williams, Mr. Charles Eugene
19            20         1       3                   Masselmani, Mrs. Fatima
26            27         0       3                   Emir, Mr. Farred Chehab
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex  Age  SibSp  Parch      Ticket    Fare Cabin Embarked  \
5      male  NaN      0      0      330877  8.4583   NaN        Q
17     male  NaN      0      0      244373      13   NaN        S
19   female  NaN      0      0        2649   7.225   NaN        C
26     male  NaN      0      0        2631   7.225   NaN        C
28   female  NaN      0      0      330959  7.8792   NaN        Q
..      ...  ...    ...    ...         ...     ...   ...      ...
859    male  NaN      0      0        2629  7.2292   NaN        C
863  female  NaN      8      2    CA. 2343   69.55   NaN        S
868    male  NaN      0      0      345777     9.5   NaN        S
878    male  NaN      0      0      349217  7.8958   NaN        S
888  female  NaN      1      2  W./C. 6607   23.45   NaN        S

     Family_Size Age_Group Title
5              1   Unknown    Mr
17             1   Unknown    Mr
19             1   Unknown   Mrs
26             1   Unknown    Mr
28             1   Unknown  Miss
..           ...       ...   ...
859            1   Unknown    Mr
863           11   Unknown  Miss
868            1   Unknown    Mr
878            1   Unknown    Mr
888            4   Unknown  Miss

[177 rows x 15 columns]

In [ ]:
# 5. Patrón de edad faltante por clase 
titanic_trabajo['Title'] = titanic_trabajo['Name'].str.extract(r',\s*([^\.]*)\.')

titanic_trabajo['AgeMissing'] = titanic_trabajo['Age'].isna()

patron = titanic_trabajo.groupby('Pclass')['AgeMissing'].mean() * 100

print("\nPorcentaje de edades faltantes por clase:\n",patron.round(2))

Porcentaje de edades faltantes por clase:
 Pclass
1    13.89
2     5.98
3    27.70
Name: AgeMissing, dtype: float64

## Ejercicio 8: Análisis avanzado

Realiza un análisis más profundo:

1. ¿Cuál fue la tasa de supervivencia por clase y sexo? (groupby con múltiples columnas)
2. ¿Cuáles fueron los 5 pasajeros que pagaron las tarifas más altas?
3. ¿Cuáles fueron los 5 sobrevivientes más jóvenes?
4. ¿Qué títulos tenían mayor tasa de supervivencia? (usa la columna Title del ejercicio 6)
5. ¿Cómo se relaciona el tamaño de familia con la supervivencia?
6. Ordena las clases por tarifa promedio de mayor a menor

In [19]:
# Tu código aquí

# 1. Supervivencia por clase y sexo
supervivencia_clase_sexo = titanic_trabajo.groupby(['Pclass', 'Sex'])['Survived'].mean() * 100
print("\nSupervivencia por clase y sexo (%):\n", supervivencia_clase_sexo)

# 2. Top 5 tarifas más altas
titanic['Fare'] = (
   titanic['Fare']
    .astype(str)
    .str.replace('.' , '') 
    )
titanic ['Fare'] = pd.to_numeric (titanic['Fare'])
top5_fares = titanic['Fare'].nlargest(5)
print("Top 5 tarifas más altas:\n", top5_fares)

# 3. Top 5 sobrevivientes más jóvenes
supervivientes_jovenes = titanic_trabajo.sort_values(by='Age', ascending=True).head(5)
print("\nTop 5 sobrevivientes más jóvenes\n",supervivientes_jovenes)

Supervivencia por clase y sexo (%):
 Pclass  Sex
1       female    96.808511
        male      36.885246
2       female    92.105263
        male      15.740741
3       female    50.000000
        male      13.544669
Name: Survived, dtype: float64
Top 5 tarifas más altas:
 258    5123292
679    5123292
737    5123292
118    2475208
299    2475208
Name: Fare, dtype: int64

Top 5 sobrevivientes más jóvenes
      PassengerId  Survived  Pclass                             Name     Sex  \
803          804         1       3  Thomas, Master. Assad Alexander    male
755          756         1       2        Hamalainen, Master. Viljo    male
644          645         1       3           Baclini, Miss. Eugenie  female
469          470         1       3    Baclini, Miss. Helene Barbara  female
78            79         1       2    Caldwell, Master. Alden Gates    male

      Age  SibSp  Parch  Ticket    Fare Cabin Embarked  Family_Size Age_Group  \
803  0.42      0      1    2625   85167   NaN        C            2     Child
755  0.67      1      1  250649     145   NaN        S            3     Child
644  0.75      2      1    2666  192583   NaN        C            4     Child
469  0.75      2      1    2666  192583   NaN        C            4     Child
78   0.83      0      2  248738      29   NaN        S            3     Child

    Fare_Category   Title
803          High  Master
755          High  Master
644          High    Miss
469          High    Miss
78         Medium  Master

In [ ]:
# 4. Supervivencia por título
supervivencia_titulo = titanic_trabajo.groupby('Title')['Survived'].mean() * 100
print("\nSupervivencia por título (%):\n", supervivencia_titulo)

# 5. Tamaño de familia vs supervivencia
fam_superv = titanic_trabajo.groupby('Family_Size')['Survived'].agg(['mean','count'])
fam_superv['survival_rate_pct'] = fam_superv['mean'] * 100
print("\nTamaño de familia vs supervivencia (% y conteo):\n", fam_superv[['survival_rate_pct','count']])

# 6. Clases ordenadas por tarifa promedio
clase_tarifa = titanic_trabajo.groupby('Pclass')['Fare'].mean().sort_values(ascending=False)
print("\nClases ordenadas por tarifa promedio (de mayor a menor):\n", clase_tarifa)

Supervivencia por título (%):
 Title
Capt          0.000000
Col          50.000000
Countess    100.000000
Don           0.000000
Dr           42.857143
Jonkheer      0.000000
Lady        100.000000
Major        50.000000
Master       57.500000
Miss         69.780220
Mlle        100.000000
Mme         100.000000
Mr           15.667311
Mrs          79.200000
Ms          100.000000
Rev           0.000000
Sir         100.000000
Name: Survived, dtype: float64

## Ejercicio 9: Manipulación de DataFrames

Practica la manipulación de la estructura del DataFrame:

1. Renombra las columnas 'Sex' a 'Gender' y 'Pclass' a 'Class'
2. Elimina las columnas 'Ticket' y 'Cabin' (tienen muchos valores faltantes)
3. Elimina las primeras 10 filas del DataFrame
4. Resetea el índice del DataFrame
5. Muestra la forma del DataFrame después de todas las modificaciones

In [20]:
# Crear una nueva copia
titanic_modificado = titanic.copy()

# Tu código aquí

# 1. Renombrar columnas
titanic_trabajo.rename(columns={'Sex':'Gender','Pclass':'Class'}).head(2)
# 2. Eliminar columnas
titanic_trabajo.drop(columns=['Ticket', 'Cabin']).head(2)
# 3. Eliminar primeras 10 filas
titanic_sin_10 = titanic_modificado.iloc[10:]
print(titanic_sin_10.head(2))

# 4. Resetear índice
tmp_after = titanic_sin_10.reset_index(drop=True).index
print("\nIndice reseteado: \n", tmp_after)
# 5. Mostrar forma final
print("\nMuestro los primero dos valores principales\n", titanic_sin_10.head(2))

    PassengerId  Survived  Pclass                             Name     Sex  \
10           11         1       3  Sandstrom, Miss. Marguerite Rut  female
11           12         1       1         Bonnell, Miss. Elizabeth  female

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked
10   4.0      1      1  PP 9549   167    G6        S
11  58.0      0      0   113783  2655  C103        S

Indice reseteado:
 RangeIndex(start=0, stop=881, step=1)

Muestro los primero dos valores principales
     PassengerId  Survived  Pclass                             Name     Sex  \
10           11         1       3  Sandstrom, Miss. Marguerite Rut  female
11           12         1       1         Bonnell, Miss. Elizabeth  female

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked
10   4.0      1      1  PP 9549   167    G6        S
11  58.0      0      0   113783  2655  C103        S

## Ejercicio 10: Proyecto Final - Informe de Supervivencia

Crea un informe completo de supervivencia del Titanic que incluya:

1. **Resumen general:**
   - Total de pasajeros
   - Total de sobrevivientes
   - Tasa de supervivencia general

2. **Análisis por demografía:**
   - Supervivencia por sexo
   - Supervivencia por clase
   - Supervivencia por grupo de edad

3. **Factores de riesgo:**
   - ¿Qué grupo tuvo mayor supervivencia?
   - ¿Qué grupo tuvo menor supervivencia?
   - Top 3 conclusiones importantes

4. **Recomendaciones:**
   - Basándote en los datos, ¿qué factores fueron más importantes para la supervivencia?

In [23]:
# Tu código aquí - Desarrolla el informe completo

print("=== INFORME DE SUPERVIVENCIA DEL TITANIC ===")
print()

# 1. RESUMEN GENERAL
print("1. RESUMEN GENERAL:")
print("===================")
print("Pasajeros abordo del titanic: ", len(titanic))
print("\nSobrevivieron un total de: ", sobrevivientes)
tasa_supervivencia = (sobrevivientes / len(titanic)) * 100
print("\nTasa de supervivencia: ",round(tasa_supervivencia,2))

=== INFORME DE SUPERVIVENCIA DEL TITANIC ===

1. RESUMEN GENERAL:
===================
Pasajeros abordo del titanic:  891

Sobrevivieron un total de:  342

Tasa de supervivencia:  38.38

2. ANÁLISIS POR DEMOGRAFÍA:
============================
Supervivencia por sexo (%):
 Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64
Supervicenvia por clase (%):
 Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64
Supervivencia por edad (%):
 Age
0.42     100.0
0.67     100.0
0.75     100.0
0.83     100.0
0.92     100.0
         ...
70.00      0.0
70.50      0.0
71.00      0.0
74.00      0.0
80.00    100.0
Name: Survived, Length: 88, dtype: float64

3. FACTORES DE RIESGO:
======================

4. RECOMENDACIONES:
===================

In [24]:
# 2. ANÁLISIS POR DEMOGRAFÍA
print("\n2. ANÁLISIS POR DEMOGRAFÍA:")
print("============================")
#supervivencia_clase_sexo /no se si esta sola valdria 
supervivencia_sexo = titanic_trabajo.groupby(['Sex'])['Survived'].mean() * 100
print("Supervivencia por sexo (%):\n", supervivencia_sexo)
supervivencia_clase = titanic_trabajo.groupby(['Pclass'])['Survived'].mean() * 100
print("Supervicenvia por clase (%):\n", supervivencia_clase)
supervivencia_edad = titanic_trabajo.groupby(['Age'])['Survived'].mean() * 100
print("Supervivencia por edad (%):\n", supervivencia_edad)

2. ANÁLISIS POR DEMOGRAFÍA:
============================
Supervivencia por sexo (%):
 Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64
Supervicenvia por clase (%):
 Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64
Supervivencia por edad (%):
 Age
0.42     100.0
0.67     100.0
0.75     100.0
0.83     100.0
0.92     100.0
         ...
70.00      0.0
70.50      0.0
71.00      0.0
74.00      0.0
80.00    100.0
Name: Survived, Length: 88, dtype: float64

In [ ]:
# Tu análisis aquí

# 3. FACTORES DE RIESGO
print("\n3. FACTORES DE RIESGO:")
print("======================")
# Tu análisis aquí
print("Clase con mayor supervivencia:\n", supervivencia_clase.idxmax())
print("Clase con menor supervivencia:\n", supervivencia_clase.idxmin())
print("3 Conclusiones:\n-Sobrebevivieron mas mujeres que hombres\n -En la primera clase hubo mayor tasa de supervivencia\n-Los niños tuvieron mayor tasa de supervivencia que los adultos\n")
# 4. RECOMENDACIONES
print("\n4. RECOMENDACIONES:")
print("===================")
print("Basandome en los datos, los siguientes puntos fueron cruciales para la supervivencia:\n -Ser mujer\n -Viajar en primera clase\n -Ser joven\n ")
# Tus conclusiones aquí

3. FACTORES DE RIESGO:
======================
Clase con mayor supervivencia:
 1
Clase con menor supervivencia:
 3

4. RECOMENDACIONES:
===================