In [1]:
import pandas as pd

In [ ]:
df_results = pd.read_csv("estadisticas.csv")

df_results.head()
print(df_results)

         Country  Population Aged 0 to 14 (%)  \
0    Afghanistan                         42.9
1        Albania                         16.8
2        Algeria                         30.3
3        Andorra                         11.9
4         Angola                         44.4
..           ...                          ...
187    Venezuela                         25.5
188      Vietnam                         23.2
189        Yemen                         41.1
190       Zambia                         41.5
191     Zimbabwe                         40.9

     Population Aged 60 and Over (%)  Population density  \
0                                3.9                65.7
1                               23.5               101.9
2                               10.0                19.7
3                               23.2               174.3
4                                4.6                30.4
..                               ...                 ...
187                             14.3                31.0
188                             13.9               322.2
189                              4.0                76.9
190                              3.3                28.7
191                              5.0                43.0

     Population(in millions)  Female Population(in millions)  \
0                      42.65                           21.12
1                       2.79                            1.41
2                      46.81                           22.94
3                       0.08                            0.04
4                      37.89                           19.14
..                       ...                             ...
187                    28.41                           14.37
188                   100.99                           51.53
189                    40.58                           20.03
190                    21.32                           10.76
191                    16.63                            8.71

     Male Population(in millions)  Sex ratio (males per 100 females)
0                           21.53                              102.0
1                            1.38                               97.8
2                           23.87                              104.1
3                            0.04                              104.6
4                           18.75                               98.0
..                            ...                                ...
187                         14.03                               97.6
188                         49.46                               96.0
189                         20.56                              102.7
190                         10.55                               98.0
191                          7.93                               91.1

[192 rows x 8 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country                            192 non-null    object
 1   Population Aged 0 to 14 (%)        192 non-null    float64
 2   Population Aged 60 and Over (%)    192 non-null    float64
 3   Population density                 192 non-null    float64
 4   Population(in millions)            192 non-null    float64
 5   Female Population(in millions)     192 non-null    float64
 6   Male Population(in millions)       192 non-null    float64
 7   Sex ratio (males per 100 females)  192 non-null    float64
dtypes: float64(7), object(1)
memory usage: 12.1+ KB

In [9]:
df_results.head()

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
0,Afghanistan,42.9,3.9,65.7,42.65,21.12,21.53,102.0
1,Albania,16.8,23.5,101.9,2.79,1.41,1.38,97.8
2,Algeria,30.3,10.0,19.7,46.81,22.94,23.87,104.1
3,Andorra,11.9,23.2,174.3,0.08,0.04,0.04,104.6
4,Angola,44.4,4.6,30.4,37.89,19.14,18.75,98.0

In [10]:
df_results.tail()

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
187,Venezuela,25.5,14.3,31.0,28.41,14.37,14.03,97.6
188,Vietnam,23.2,13.9,322.2,100.99,51.53,49.46,96.0
189,Yemen,41.1,4.0,76.9,40.58,20.03,20.56,102.7
190,Zambia,41.5,3.3,28.7,21.32,10.76,10.55,98.0
191,Zimbabwe,40.9,5.0,43.0,16.63,8.71,7.93,91.1

In [11]:
df_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country                            192 non-null    object
 1   Population Aged 0 to 14 (%)        192 non-null    float64
 2   Population Aged 60 and Over (%)    192 non-null    float64
 3   Population density                 192 non-null    float64
 4   Population(in millions)            192 non-null    float64
 5   Female Population(in millions)     192 non-null    float64
 6   Male Population(in millions)       192 non-null    float64
 7   Sex ratio (males per 100 females)  192 non-null    float64
dtypes: float64(7), object(1)
memory usage: 12.1+ KB

In [13]:
df_results.describe()

,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
count,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000
mean,26.308333,14.167188,348.131771,42.267812,21.012708,21.255156,101.186458
std,10.328998,9.106158,1969.940293,151.787795,74.169644,77.631324,16.366059
min,10.600000,3.300000,2.200000,0.010000,0.000000,0.000000,85.200000
25%,17.000000,6.100000,36.550000,2.180000,1.037500,1.082500,95.950000
50%,24.650000,11.250000,90.300000,9.455000,4.720000,4.660000,98.700000
75%,36.350000,22.250000,209.725000,32.467500,15.750000,16.387500,101.400000
max,49.000000,43.500000,25926.800000,1450.940000,702.610000,748.320000,248.200000

In [ ]:
df_results[['Country', 'Female Population(in millions)']]

         Country  Female Population(in millions)
0    Afghanistan                           21.12
1        Albania                            1.41
2        Algeria                           22.94
3        Andorra                            0.04
4         Angola                           19.14
..           ...                             ...
187    Venezuela                           14.37
188      Vietnam                           51.53
189        Yemen                           20.03
190       Zambia                           10.76
191     Zimbabwe                            8.71

[192 rows x 2 columns]

In [16]:
df_results[df_results['Country'] == 'Tuvalu']

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
176,Tuvalu,32.9,11.1,321.5,0.01,0.0,0.0,104.8

In [20]:
df_results[(df_results['Female Population(in millions)'] < 0.05) & (df_results['Sex ratio (males per 100 females)']<92)]

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
143,Saint Kitts and Nevis,18.2,17.1,180.2,0.05,0.02,0.02,91.8

In [ ]:
df_results['Population Aged 60 and Over (%)'].max()

#df_results.groupby('Country')['Population Aged 60 and Over (%)'].mean()

Country
Afghanistan     3.9
Albania        23.5
Algeria        10.0
Andorra        23.2
Angola          4.6
               ...
Venezuela      14.3
Vietnam        13.9
Yemen           4.0
Zambia          3.3
Zimbabwe        5.0
Name: Population Aged 60 and Over (%), Length: 192, dtype: float64

In [35]:
df_results['Poblacion entre 0 y 14 (en millones)'] = df_results['Population(in millions)'] * df_results['Population Aged 0 to 14 (%)'] /100
df_results.head()

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females),Si tiene mas mujeres,Poblacion entre 0 y 14 (en millones)
0,Afghanistan,42.9,3.9,65.7,42.65,21.12,21.53,102.0,False,18.29685
1,Albania,16.8,23.5,101.9,2.79,1.41,1.38,97.8,True,0.46872
2,Algeria,30.3,10.0,19.7,46.81,22.94,23.87,104.1,False,14.18343
3,Andorra,11.9,23.2,174.3,0.08,0.04,0.04,104.6,False,0.00952
4,Angola,44.4,4.6,30.4,37.89,19.14,18.75,98.0,True,16.82316

In [34]:
df_results['Si tiene mas mujeres'] = df_results['Female Population(in millions)'] > df_results['Male Population(in millions)']
df_results.head()

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females),Si tiene mas mujeres
0,Afghanistan,42.9,3.9,65.7,42.65,21.12,21.53,102.0,False
1,Albania,16.8,23.5,101.9,2.79,1.41,1.38,97.8,True
2,Algeria,30.3,10.0,19.7,46.81,22.94,23.87,104.1,False
3,Andorra,11.9,23.2,174.3,0.08,0.04,0.04,104.6,False
4,Angola,44.4,4.6,30.4,37.89,19.14,18.75,98.0,True

In [40]:
df_ine = pd.read_csv("ineGastoAutonomia.csv", sep=";", encoding='latin-1')

In [41]:
df_ine.head()

,Comunidades y Ciudades Autónomas de destino,País de residencia,Periodo,Total
0,Andalucía,Total,2025T2,"443,24"
1,Andalucía,Total,2025T1,"500,83"
2,Andalucía,Total,2024T4,"451,81"
3,Andalucía,Total,2024T3,"483,88"
4,Andalucía,Total,2024T2,"433,29"

In [42]:
df_ine['País de residencia'].value_counts()

País de residencia
Total                        570
Alemania                     570
Andorra                      570
Austria                      570
Bélgica                      570
Dinamarca                    570
Finlandia                    570
Francia                      570
Irlanda                      570
Italia                       570
Noruega                      570
Países Bajos                 570
Polonia                      570
Portugal                     570
Reino Unido                  570
Rumanía                      570
Rusia                        570
Suecia                       570
Suiza                        570
Otros Países Europeos        570
Argentina                    570
Brasil                       570
Canadá                       570
Chile                        570
Colombia                     570
Estados Unidos de América    570
México                       570
Resto de América             570
Australia                    570
China                        570
Corea                        570
Emiratos Árabes Unidos       570
Japón                        570
Turquía                      570
Resto del mundo              570
Name: count, dtype: int64

In [43]:
df_ine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19950 entries, 0 to 19949
Data columns (total 4 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Comunidades y Ciudades Autónomas de destino  19950 non-null  object
 1   País de residencia                           19950 non-null  object
 2   Periodo                                      19950 non-null  object
 3   Total                                        19950 non-null  object
dtypes: object(4)
memory usage: 623.6+ KB

In [44]:
df_ine.describe()

,Comunidades y Ciudades Autónomas de destino,País de residencia,Periodo,Total
count,19950,19950,19950,19950
unique,19,35,30,14987
top,Andalucía,Total,2025T2,.
freq,1050,570,665,3209

In [52]:
df_ine['Comunidades y Ciudades Autónomas de destino'].value_counts()

Comunidades y Ciudades Autónomas de destino
Andalucía                      1050
Aragón                         1050
Asturias, Principado de        1050
Balears, Illes                 1050
Canarias                       1050
Cantabria                      1050
Castilla y León                1050
Castilla - La Mancha           1050
Cataluña                       1050
Comunitat Valenciana           1050
Extremadura                    1050
Galicia                        1050
Madrid, Comunidad de           1050
Murcia, Región de              1050
Navarra, Comunidad Foral de    1050
País Vasco                     1050
Rioja, La                      1050
Ceuta                          1050
Melilla                        1050
Name: count, dtype: int64

In [ ]:
df_euskadi = df_ine[df_ine['Comunidades y Ciudades Autónomas de destino']=='País Vasco']
df_euskadi.head()

,Comunidades y Ciudades Autónomas de destino,País de residencia,Periodo,Total
15750,País Vasco,Total,2025T2,"194,20"
15751,País Vasco,Total,2025T1,"175,37"
15752,País Vasco,Total,2024T4,"184,51"
15753,País Vasco,Total,2024T3,"162,84"
15754,País Vasco,Total,2024T2,"192,08"

In [55]:
df_euskadi['Comunidades y Ciudades Autónomas de destino'].value_counts()

Comunidades y Ciudades Autónomas de destino
País Vasco    1050
Name: count, dtype: int64